import type { BlockOutput, ExportFormat } from "./export-types";
import { CREDIT_URL, SITE_NAME } from "@/lib/site";

export type { ExportFormat };

/**
 * "חותמת יצרן" - כל קוד שיוצא מהאתר נושא קרדיט ל-WEblok: הערה בראש כל קובץ,
 * ומאפייני data-* על עטיפת הבלוק (data-generator / data-weblok-block), כך
 * שאפשר לזהות בלוק של WEblok גם אחרי שההערות נמחקו ע"י minifier.
 */
const commentSafe = (v: string) => v.replace(/-{2,}/g, "-").replace(/[<>]/g, "").replace(/\*\//g, "");

function creditLines(out: BlockOutput): string[] {
  return [
    `${commentSafe(out.componentName)} · Generated by ${SITE_NAME} — ${commentSafe(CREDIT_URL)}`,
    `נוצר באמצעות ${SITE_NAME} · עצמאי לגמרי, בלי תלות בשרת שלנו`,
  ];
}

const htmlCredit = (out: BlockOutput) => `<!--\n  ${creditLines(out).join("\n  ")}\n-->`;
const blockCredit = (out: BlockOutput) => `/*!\n * ${creditLines(out).join("\n * ")}\n */`;
const lineCredit = (out: BlockOutput) => creditLines(out).map((l) => `// ${l}`).join("\n");

function wrapperAttrs(out: BlockOutput, attr: "class" | "className" = "class") {
  return `${attr}="${wrapperClass(out)}" data-weblok-block="${slug(out.componentName)}" data-generator="${SITE_NAME}"`;
}

export function wrapperClass(out: BlockOutput) {
  return `weblok-${slug(out.componentName)}`;
}

/** עוטף CSS ב-<style> וה-JS (אם יש) ב-<script>, לפורמט "html" המאוחד. */
export function toUnifiedHtml(out: BlockOutput): string {
  const script = out.js ? `\n<script>\n${indent(out.js, 2)}\n</script>` : "";
  return `${htmlCredit(out)}
<div ${wrapperAttrs(out)}>
${indent(out.html.trim(), 2)}
</div>
<style>
${indent(out.css.trim(), 2)}
</style>${script}
<!-- /${SITE_NAME}: ${commentSafe(out.componentName)} -->`;
}

/** שלושה קבצים נפרדים - HTML (שכבר מקשר את שני האחרים) + CSS + JS. */
export function toSplitFiles(out: BlockOutput): { html: string; css: string; js: string } {
  const js = out.js?.trim() ?? "";
  const scriptTag = js ? `\n<script src="script.js" defer></script>` : "";
  return {
    html: `${htmlCredit(out)}
<!-- שמרו את style.css ו-script.js באותה תיקייה עם הקובץ הזה -->
<link rel="stylesheet" href="style.css">
<div ${wrapperAttrs(out)}>
${indent(out.html.trim(), 2)}
</div>${scriptTag}`,
    css: `${blockCredit(out)}\n${out.css.trim()}\n`,
    js: js ? `${lineCredit(out)}\n${js}\n` : "",
  };
}

/** תוכן בתוך template literal של JS: בורחים מ-\, מ-` ומ-${ */
const templateSafe = (s: string) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

/**
 * רכיב React עצמאי. ה-HTML נטען כמו שהוא (dangerouslySetInnerHTML) במקום
 * תרגום ל-JSX - תרגום אוטומטי שובר תגיות לא סגורות (<input>), style כמחרוזת
 * ומאפייני SVG. ה-JS של הבלוק רץ ב-useEffect אחרי שה-HTML כבר ב-DOM, ומוגן
 * מהרצה כפולה (StrictMode) ע"י הדגל data-wb-init שכל בלוק מציב.
 */
export function toJsx(out: BlockOutput): string {
  const js = out.js?.trim();
  const effect = js
    ? `
  useEffect(() => {
${indent(js, 4)}
  }, []);
`
    : "";
  const importLine = js ? `import { useEffect } from "react";\n\n` : "";
  return `${lineCredit(out)}
${importLine}const CSS = \`
${templateSafe(out.css.trim())}
\`;

const HTML = \`
${templateSafe(out.html.trim())}
\`;

export default function ${out.componentName}() {${effect}
  return (
    <>
      <style>{CSS}</style>
      <div ${wrapperAttrs(out, "className")} dangerouslySetInnerHTML={{ __html: HTML }} />
    </>
  );
}
`;
}

/** נקודת הכניסה היחידה שה-UI קורא לה - "תן לי את הבלוק בפורמט X". */
export interface ExportResult {
  kind: "single" | "multi";
  files: Record<string, string>;
}

export function exportBlock(out: BlockOutput, format: ExportFormat): ExportResult {
  let files: Record<string, string>;
  if (format === "html") files = { "index.html": toUnifiedHtml(out) };
  else if (format === "html-css-js") {
    const f = toSplitFiles(out);
    files = { "index.html": f.html, "style.css": f.css };
    if (f.js) files["script.js"] = f.js;
  } else files = { [`${out.componentName}.jsx`]: toJsx(out) };

  if (out.extraFiles) files = { ...files, ...out.extraFiles };
  return { kind: Object.keys(files).length > 1 ? "multi" : "single", files };
}

function indent(s: string, spaces: number) {
  const pad = " ".repeat(spaces);
  return s
    .split("\n")
    .map((l) => (l ? pad + l : l))
    .join("\n");
}

function slug(name: string) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}
