import type { FieldDef, BlockValues } from "../types";
import { FONT_HINT, FONT_OPTIONS } from "../_shared/util";

export const fields: FieldDef[] = [
  {
    id: "submitMethod",
    label: "יעד שליחת ההודעה",
    type: "select",
    icon: "fa-paper-plane",
    default: "formspree",
    group: "יעד",
    options: [
      { value: "formspree", label: "מייל ע\"י Formspree" },
      { value: "webhook", label: "Webhook (Make / n8n / Zapier)" },
      { value: "mailto", label: "פותח את המייל של המבקר (בלי שרת בכלל)" },
    ],
  },
  {
    id: "formspreeId",
    label: "Formspree Form ID",
    type: "text",
    icon: "fa-key",
    default: "",
    group: "יעד",
    dependsOn: { field: "submitMethod", equals: ["formspree"] },
    hint: 'המזהה שקיבלתם מ-Formspree נראה כך: https://formspree.io/f/xbfnqqla - הכניסו רק את הקטע האחרון (xbfnqqla).',
  },
  {
    id: "webhookUrl",
    label: "כתובת Webhook",
    type: "text",
    icon: "fa-link",
    default: "",
    group: "יעד",
    dependsOn: { field: "submitMethod", equals: ["webhook"] },
    hint: "הכתובת המלאה שקיבלתם מ-Make/n8n/Zapier, למשל: https://hook.eu1.make.com/abc123.",
  },
  {
    id: "mailtoAddress",
    label: "כתובת מייל יעד",
    type: "text",
    icon: "fa-envelope",
    default: "",
    group: "יעד",
    dependsOn: { field: "submitMethod", equals: ["mailto"] },
    hint: "לאן ההודעה תישלח - יישום המייל של המבקר ייפתח עם הכתובת הזו כבר ממולאת.",
  },
  {
    id: "sectionTitle",
    aiAssist: true,
    label: "כותרת מדור (מעל הכרטיס)",
    type: "text",
    icon: "fa-heading",
    default: "",
    group: "תוכן",
    dependsOn: { field: "displayMode", equals: ["block"] },
    hint: "רשות. כותרת לכל הסקשן, מחוץ לכרטיס הטופס. מוצג רק במצב \"בלוק מובנה\".",
  },
  {
    id: "formTitle",
    aiAssist: true,
    label: "כותרת הטופס",
    type: "text",
    icon: "fa-paper-plane",
    default: "צור עמנו קשר",
    group: "תוכן",
  },
  {
    id: "formSubtitle",
    aiAssist: true,
    label: "תת-כותרת",
    type: "textarea",
    icon: "fa-paragraph",
    default: "נשמח לשמוע ממך! מלא את הפרטים ונחזור אליך בהקדם.",
    group: "תוכן",
  },
  {
    id: "btnText",
    label: "טקסט כפתור שליחה",
    type: "text",
    icon: "fa-paper-plane",
    default: "שלח הודעה",
    group: "תוכן",
  },
  {
    id: "successMsg",
    aiAssist: true,
    label: "הודעת הצלחה",
    type: "text",
    icon: "fa-circle-check",
    default: "הודעתך נשלחה בהצלחה! נחזור אליך בהקדם.",
    group: "תוכן",
  },
  {
    id: "showPhone",
    aiDesignEditable: true,
    label: "שדה טלפון",
    type: "select",
    icon: "fa-phone",
    default: "optional",
    group: "שדות",
    options: [
      { value: "optional", label: "מוצג (רשות)" },
      { value: "required", label: "מוצג (חובה)" },
      { value: "hidden", label: "מוסתר" },
    ],
  },
  {
    id: "showSubject",
    aiDesignEditable: true,
    label: "שדה נושא",
    type: "select",
    icon: "fa-bookmark",
    default: "optional",
    group: "שדות",
    options: [
      { value: "optional", label: "מוצג (רשות)" },
      { value: "required", label: "מוצג (חובה)" },
      { value: "hidden", label: "מוסתר" },
    ],
  },
  {
    id: "displayMode",
    aiDesignEditable: true,
    label: "מצב תצוגה",
    type: "select",
    icon: "fa-desktop",
    default: "block",
    group: "תצוגה",
    options: [
      { value: "block", label: "בלוק מובנה (סקשן בעמוד)" },
      { value: "widget", label: "ווידג'ט/בועה צפה" },
    ],
  },
  {
    id: "widgetPosition",
    label: "מיקום הווידג'ט",
    type: "select",
    icon: "fa-location-dot",
    default: "right",
    group: "תצוגה",
    dependsOn: { field: "displayMode", equals: ["widget"] },
    aiDesignEditable: true,
    options: [
      { value: "right", label: "ימין למטה" },
      { value: "left", label: "שמאל למטה" },
    ],
  },
  {
    id: "formStyle",
    aiDesignEditable: true,
    label: "סגנון שדות",
    type: "select",
    icon: "fa-pen-to-square",
    default: "floating",
    group: "עיצוב",
    options: [
      { value: "floating", label: "תוויות צפות (מודרני)" },
      { value: "classic", label: "קלאסי - תווית מעל השדה" },
      { value: "underline", label: "מינימלי - קו תחתון" },
    ],
  },
  {
    id: "themeSelect",
    aiDesignEditable: true,
    label: "סגנון עיצוב",
    type: "select",
    icon: "fa-palette",
    default: "glass",
    group: "עיצוב",
    options: [
      { value: "glass", label: "זכוכית מודרנית" },
      { value: "cyber", label: "סייברפאנק" },
      { value: "ios", label: "סגנון אפל" },
      { value: "material", label: "Google Material" },
      { value: "ocean", label: "אוקיינוס" },
      { value: "neon", label: "ניאון עתידני" },
      { value: "retro", label: "רטרו" },
    ],
  },
  {
    id: "defaultThemeMode",
    aiDesignEditable: true,
    label: "מצב תצוגה התחלתי",
    type: "select",
    icon: "fa-circle-half-stroke",
    default: "dark",
    group: "עיצוב",
    options: [
      { value: "dark", label: "כהה" },
      { value: "light", label: "בהיר" },
    ],
  },
  {
    id: "allowThemeToggle",
    aiDesignEditable: true,
    label: "כפתור שינוי עיצוב (יום/לילה)",
    type: "select",
    icon: "fa-toggle-on",
    default: "yes",
    group: "עיצוב",
    options: [
      { value: "yes", label: "מוצג" },
      { value: "no", label: "מוסתר" },
    ],
  },
  {
    id: "accentColor",
    aiDesignEditable: true,
    label: "צבע מרכזי",
    type: "color",
    icon: "fa-eye-dropper",
    default: "#38bdf8",
    group: "עיצוב",
  },
  {
    id: "fontSelect",
    aiDesignEditable: true,
    label: "גופן",
    type: "select",
    icon: "fa-font",
    default: "system",
    group: "עיצוב",
    hint: FONT_HINT,
    options: FONT_OPTIONS,
  },
];

export function defaultValues(): BlockValues {
  const values: BlockValues = {};
  fields.forEach((f) => (values[f.id] = f.default));
  return values;
}
