/**
 * טקסטי הממשק של האתר המיוצא (לא של WEblok) - נכתבים לפרויקט כ-lib/strings.ts
 * דרך JSON.stringify, ומשמשים גם את התצוגה המקדימה.
 */
export const SITE_STRINGS = {
  he: {
    type: {
      wedding: "חתונה",
      mitzvah: "בר/בת מצווה",
      brit: "ברית",
      birthday: "יום הולדת",
      corporate: "אירוע חברה",
      other: "הזמנה",
    },
    date: "תאריך",
    time: "שעה",
    navigate: "ניווט",
    waze: "ניווט ב-Waze",
    maps: "Google Maps",
    calendar: "הוספה ליומן",
    rsvpTitle: "אישור הגעה",
    rsvpUntil: "נשמח לתשובה עד {date}",
    rsvpClosed: "מועד אישורי ההגעה הסתיים. לשינויים - צרו קשר עם המארחים.",
    name: "שם מלא",
    phone: "טלפון",
    optional: "(לא חובה)",
    attending: "האם תגיעו?",
    yes: "מגיעים 🎉",
    no: "לא נוכל להגיע",
    maybe: "עדיין לא בטוחים",
    guests: "כמה תגיעו? (כולל אתכם)",
    note: "הערה / בקשה (אלרגיות, הסעה...)",
    submit: "שליחת אישור",
    sending: "שולח...",
    thanks: "תודה! קיבלנו את התשובה שלכם",
    again: "שליחת תשובה נוספת",
    errInvalid: "נא לבדוק את השדות המסומנים",
    errRate: "יותר מדי ניסיונות. נסו שוב בעוד כמה דקות.",
    errClosed: "מועד אישורי ההגעה הסתיים",
    errServer: "משהו השתבש. נסו שוב.",
    previewNote: "זוהי תצוגה מקדימה - השליחה פעילה רק באתר המוכן",
    admin: {
      title: "ניהול אישורי הגעה",
      login: "כניסה",
      password: "סיסמת מנהל",
      wrong: "סיסמה שגויה",
      tooMany: "יותר מדי ניסיונות. נסו שוב מאוחר יותר.",
      notConfigured: "האדמין לא הוגדר. יש להגדיר ב-Vercel את ADMIN_PASSWORD (לפחות 10 תווים) ואת ADMIN_SESSION_SECRET (לפחות 32 תווים).",
      dbError: "אין חיבור למסד הנתונים. בדקו את SUPABASE_URL ו-SUPABASE_SECRET_KEY, ושהרצתם את supabase/schema.sql.",
      logout: "יציאה",
      exportCsv: "ייצוא CSV (אקסל)",
      responses: "תשובות",
      coming: "מגיעים",
      guests: "סה״כ אורחים",
      maybe: "אולי",
      notComing: "לא מגיעים",
      filterAll: "הכל",
      search: "חיפוש שם / טלפון",
      empty: "עדיין אין תשובות",
      colDate: "נשלח",
      colName: "שם",
      colPhone: "טלפון",
      colStatus: "סטטוס",
      colGuests: "מגיעים",
      colNote: "הערה",
      delete: "מחיקה",
      confirmDelete: "למחוק את התשובה של {name}?",
      deleteFailed: "המחיקה נכשלה",
      viewSite: "לדף ההזמנה",
    },
  },
  en: {
    type: {
      wedding: "Wedding",
      mitzvah: "Bar / Bat Mitzvah",
      brit: "Brit Milah",
      birthday: "Birthday",
      corporate: "Company event",
      other: "Invitation",
    },
    date: "Date",
    time: "Time",
    navigate: "Directions",
    waze: "Navigate with Waze",
    maps: "Google Maps",
    calendar: "Add to calendar",
    rsvpTitle: "RSVP",
    rsvpUntil: "Kindly reply by {date}",
    rsvpClosed: "RSVP is closed. For changes please contact the hosts.",
    name: "Full name",
    phone: "Phone",
    optional: "(optional)",
    attending: "Will you attend?",
    yes: "Yes, we'll be there 🎉",
    no: "Sorry, can't make it",
    maybe: "Not sure yet",
    guests: "How many of you? (including you)",
    note: "Note / request (allergies, ride...)",
    submit: "Send RSVP",
    sending: "Sending...",
    thanks: "Thank you! We got your reply",
    again: "Send another reply",
    errInvalid: "Please check the highlighted fields",
    errRate: "Too many attempts. Please try again in a few minutes.",
    errClosed: "RSVP is closed",
    errServer: "Something went wrong. Please try again.",
    previewNote: "This is a preview - submitting works on the deployed site",
    admin: {
      title: "RSVP admin",
      login: "Sign in",
      password: "Admin password",
      wrong: "Wrong password",
      tooMany: "Too many attempts. Please try again later.",
      notConfigured: "Admin is not configured. Set ADMIN_PASSWORD (10+ chars) and ADMIN_SESSION_SECRET (32+ chars) in Vercel.",
      dbError: "No database connection. Check SUPABASE_URL and SUPABASE_SECRET_KEY, and that supabase/schema.sql was run.",
      logout: "Sign out",
      exportCsv: "Export CSV (Excel)",
      responses: "Responses",
      coming: "Attending",
      guests: "Total guests",
      maybe: "Maybe",
      notComing: "Not attending",
      filterAll: "All",
      search: "Search name / phone",
      empty: "No responses yet",
      colDate: "Sent",
      colName: "Name",
      colPhone: "Phone",
      colStatus: "Status",
      colGuests: "Guests",
      colNote: "Note",
      delete: "Delete",
      confirmDelete: "Delete the response from {name}?",
      deleteFailed: "Delete failed",
      viewSite: "Invitation page",
    },
  },
} as const;

export type SiteStrings = (typeof SITE_STRINGS)["he"];

/** "יום חמישי, 17 בדצמבר 2026" - התאריך מפורש כצהריים UTC כדי שלא "יזוז" יום בגלל אזור זמן. */
export function formatEventDate(date: string, lang: "he" | "en"): string {
  if (!date) return "";
  const d = new Date(`${date}T12:00:00Z`);
  if (Number.isNaN(d.getTime())) return date;
  return new Intl.DateTimeFormat(lang === "he" ? "he-IL" : "en-US", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  }).format(d);
}
